"use client";

import { useState } from "react";
import {
  PieChart,
  Search,
  TrendingUp,
  CalendarClock,
  Rocket,
  ArrowRight,
  Download,
  CheckCircle,
  UserPlus,
  Check,
  ChevronDown,
  Calendar,
  MessageSquare,
  FileText,
  PlusCircle,
  Calculator,
} from "lucide-react";

export default function PricingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const faqItems = [
    {
      question: "Why don't you display pricing on your website?",
      answer:
        "Every agency has unique needs—different markets, client volumes, and growth goals. Rather than forcing you into a one-size-fits-all package, we customize pricing to ensure you get the best value for your specific situation.",
    },
    {
      question: "What's included in the setup fee?",
      answer:
        "The setup fee covers platform integration, white-label configuration, marketing materials, team training, and initial algorithm deployment. Everything you need to launch your branded trading platform.",
    },
    {
      question: "How do performance fees work?",
      answer:
        "Performance fees are a small percentage of trading profits generated by your clients. If your clients don't profit in a given period, you don't pay performance fees for that period. This aligns our success with yours.",
    },
    {
      question: "Can I start small and scale up?",
      answer:
        "Absolutely. Most partners start with the Starter tier and upgrade as their client base grows. Your pricing structure is designed to scale favorably as you add more clients and markets.",
    },
    {
      question: "Do you charge my clients directly?",
      answer:
        "No. We only have a relationship with you, the agency partner. How you structure pricing for your own clients is entirely up to you, giving you full control over your margins.",
    },
  ];

  return (
    <section className="relative bg-[#020408] border-y border-white/5 overflow-hidden">
      {/* Background Gradients */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none -z-10">
        <div className="absolute top-[-10%] left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-blue-600/20 rounded-full blur-[120px] opacity-20 mix-blend-screen" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[800px] h-[600px] bg-indigo-600/10 rounded-full blur-[100px] opacity-20" />
      </div>

      {/* Hero */}
      <div className="border-white/5 border-b pt-20 px-6 pb-32 relative">
        <div className="max-w-7xl mx-auto">
          {/* Hero Section */}
          <div className="text-center max-w-4xl mx-auto mb-20 relative z-10">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-semibold uppercase tracking-wider mb-6">
              Partnership Program
            </div>
            <h1 className="text-4xl md:text-6xl font-semibold text-white tracking-tight mb-6 leading-[1.1]">
              Flexible Pricing Built for{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-400">
                Agency Growth
              </span>
            </h1>
            <p className="text-lg text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
              Transparent, scalable pricing that grows with your business—no
              hidden fees. Custom pricing based on your agency&apos;s needs and
              client base.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-8">
              <button className="px-8 py-4 bg-white text-[#020408] rounded-full font-semibold hover:bg-slate-200 transition-all shadow-lg shadow-white/10 flex items-center gap-2">
                Schedule Pricing Consultation
                <ArrowRight className="w-4 h-4" />
              </button>
              <button className="px-8 py-4 bg-[#0B0E14] text-white border border-white/10 rounded-full font-semibold hover:bg-white/5 transition-all flex items-center gap-2">
                <Download className="w-4 h-4" />
                Download Partnership Guide
              </button>
            </div>
            <p className="text-sm text-slate-500 flex items-center justify-center gap-2">
              <CheckCircle className="w-4 h-4 text-emerald-500" />
              Trusted by 500+ agencies worldwide
            </p>
          </div>

          {/* Pricing Philosophy */}
          <div className="mb-24">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-semibold text-white mb-4">
                Pricing That Aligns With Your Success
              </h2>
              <p className="text-slate-400 max-w-2xl mx-auto">
                We believe in transparent, fair pricing that scales with your
                agency. No one-size-fits-all packages—your pricing reflects your
                specific needs.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                {
                  icon: PieChart,
                  color: "blue",
                  title: "Profit Share",
                  desc: "Small % of trading profits. If clients don't profit, we don't charge this.",
                },
                {
                  icon: Search,
                  color: "emerald",
                  title: "Transparent Structure",
                  desc: "Clear fee structure with no hidden costs. Know exactly what you're paying for.",
                },
                {
                  icon: TrendingUp,
                  color: "indigo",
                  title: "Volume Discounts",
                  desc: "As you scale your client base, your per-unit costs decrease significantly.",
                },
                {
                  icon: CalendarClock,
                  color: "purple",
                  title: "Flexible Terms",
                  desc: "Payment options designed to support your cash flow during the startup phase.",
                },
              ].map((item, i) => {
                const Icon = item.icon;
                return (
                  <div
                    key={i}
                    className="p-6 rounded-xl bg-[#0B0E14] border border-white/5 hover:border-white/10 transition-colors"
                  >
                    <div
                      className={`w-10 h-10 rounded-lg bg-${item.color}-500/10 flex items-center justify-center mb-4 text-${item.color}-400`}
                    >
                      <Icon className="w-5 h-5" />
                    </div>
                    <h3 className="text-white font-semibold mb-2">
                      {item.title}
                    </h3>
                    <p className="text-sm text-slate-400">{item.desc}</p>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Pricing Components */}
          <div className="mb-24">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-semibold text-white mb-4">
                Understanding Our Pricing Structure
              </h2>
              <p className="text-slate-400">
                Two simple components that make up your partnership investment
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {/* Component 1: Setup Fee */}
              <div className="rounded-2xl bg-[#0B0E14] border border-white/10 overflow-hidden">
                <div className="p-8 border-b border-white/5 bg-gradient-to-r from-blue-900/10 to-transparent">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-12 h-12 rounded-full bg-blue-500 text-white flex items-center justify-center shadow-lg shadow-blue-500/20">
                      <Rocket className="w-6 h-6" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-white">
                        Initial Setup & Integration
                      </h3>
                      <p className="text-sm text-slate-400">
                        One-time fee to launch your platform
                      </p>
                    </div>
                  </div>
                </div>

                <div className="p-8 space-y-8">
                  <div>
                    <h4 className="text-sm font-medium text-slate-300 uppercase tracking-wide mb-4">
                      What Determines Your Fee?
                    </h4>

                    <div className="space-y-6">
                      {/* Factor 1 */}
                      <div>
                        <div className="flex justify-between text-sm mb-2">
                          <span className="text-slate-400">
                            Asset Classes Selected
                          </span>
                          <span className="text-blue-400 font-medium">
                            Choose Your Markets
                          </span>
                        </div>
                        <div className="grid grid-cols-4 gap-2">
                          <div className="h-10 border border-blue-500/50 bg-blue-500/10 rounded flex items-center justify-center text-xs font-semibold text-blue-400">
                            FOREX
                          </div>
                          <div className="h-10 border border-white/10 bg-white/5 rounded flex items-center justify-center text-xs font-medium text-slate-500">
                            CRYPTO
                          </div>
                          <div className="h-10 border border-white/10 bg-white/5 rounded flex items-center justify-center text-xs font-medium text-slate-500">
                            STOCKS
                          </div>
                          <div className="h-10 border border-white/10 bg-white/5 rounded flex items-center justify-center text-xs font-medium text-slate-500">
                            FUTURES
                          </div>
                        </div>
                      </div>

                      {/* Factor 2 */}
                      <div>
                        <div className="flex justify-between text-sm mb-2">
                          <span className="text-slate-400">
                            Algorithm Library Access
                          </span>
                          <span className="text-white font-medium">
                            Starter vs Full Access
                          </span>
                        </div>
                        <div className="h-2 bg-white/10 rounded-full overflow-hidden">
                          <div className="h-full w-2/3 bg-gradient-to-r from-blue-500 to-indigo-500 rounded-full" />
                        </div>
                        <div className="flex justify-between text-xs text-slate-500 mt-2">
                          <span>10 Strategies</span>
                          <span>30+ Strategies</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/5 rounded-xl p-4 border border-white/5">
                    <h4 className="text-sm font-medium text-white mb-3">
                      Everything Included:
                    </h4>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-slate-400">
                      {[
                        "Platform Integration",
                        "Marketing Materials",
                        "White-label Config",
                        "Team Training",
                      ].map((item) => (
                        <div
                          key={item}
                          className="flex items-center gap-2"
                        >
                          <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                          {item}
                        </div>
                      ))}
                    </div>
                  </div>

                  <button className="w-full py-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-lg font-medium transition-colors">
                    Get Your Custom Quote
                  </button>
                </div>
              </div>

              {/* Component 2: Performance Fee */}
              <div className="rounded-2xl bg-[#0B0E14] border border-white/10 overflow-hidden">
                <div className="p-8 border-b border-white/5 bg-gradient-to-r from-emerald-900/10 to-transparent">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-12 h-12 rounded-full bg-emerald-500 text-white flex items-center justify-center shadow-lg shadow-emerald-500/20">
                      <TrendingUp className="w-6 h-6" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-white">
                        Success-Based Performance
                      </h3>
                      <p className="text-sm text-slate-400">
                        Aligned incentives for mutual growth
                      </p>
                    </div>
                  </div>
                </div>

                <div className="p-8 space-y-8">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
                      <div className="w-8 h-8 rounded bg-emerald-500/10 text-emerald-400 flex items-center justify-center mb-3">
                        <UserPlus className="w-4 h-4" />
                      </div>
                      <h4 className="text-white font-medium mb-1">
                        Client Activation
                      </h4>
                      <p className="text-xs text-slate-400 leading-relaxed">
                        Small fixed fee per new client account setup. Simple,
                        predictable cost.
                      </p>
                    </div>
                    <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
                      <div className="w-8 h-8 rounded bg-indigo-500/10 text-indigo-400 flex items-center justify-center mb-3">
                        <PieChart className="w-4 h-4" />
                      </div>
                      <h4 className="text-white font-medium mb-1">
                        Profit Share
                      </h4>
                      <p className="text-xs text-slate-400 leading-relaxed">
                        Small % of trading profits. If clients don&apos;t
                        profit, we don&apos;t charge this.
                      </p>
                    </div>
                  </div>

                  <div className="relative py-4">
                    <div
                      className="absolute inset-0 flex items-center"
                      aria-hidden="true"
                    >
                      <div className="w-full border-t border-white/5" />
                    </div>
                    <div className="relative flex justify-center">
                      <span className="bg-[#0B0E14] px-4 text-xs font-medium text-slate-500">
                        WHY THIS WORKS
                      </span>
                    </div>
                  </div>

                  <ul className="space-y-3">
                    {[
                      "We're directly invested in your clients' success",
                      "Lower upfront risk for your agency",
                      "Transparent tracking through partner dashboard",
                    ].map((item, i) => (
                      <li key={i} className="flex items-start gap-3">
                        <Check className="w-4 h-4 text-emerald-500 mt-0.5" />
                        <span className="text-sm text-slate-300">{item}</span>
                      </li>
                    ))}
                  </ul>

                  <button className="w-full py-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-lg font-medium transition-colors">
                    Discuss Your Fee Structure
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Pricing Factors Visual */}
          <div className="mb-24">
            <div className="relative bg-[#0B0E14] border border-white/5 rounded-2xl p-8 md:p-12 overflow-hidden">
              <div className="absolute top-0 right-0 w-96 h-96 bg-blue-600/5 rounded-full blur-3xl -z-10" />

              <div className="text-center mb-10">
                <h3 className="text-2xl font-semibold text-white mb-2">
                  What Determines Your Investment?
                </h3>
                <p className="text-slate-400">
                  Every agency is unique—your pricing reflects your specific path
                </p>
              </div>

              <div className="flex flex-col md:flex-row items-center justify-center gap-6 relative z-10">
                {/* Step 1 */}
                <div className="bg-[#020408] border border-white/10 p-6 rounded-xl w-full md:w-64 h-48 flex flex-col items-center justify-center text-center group hover:border-blue-500/30 transition-all">
                  <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center mb-4 text-white font-bold group-hover:bg-blue-600 transition-colors">
                    1
                  </div>
                  <h4 className="text-white font-medium mb-1">Agency Goals</h4>
                  <p className="text-xs text-slate-500">
                    Client volume & growth targets
                  </p>
                </div>

                {/* Arrow */}
                <div className="hidden md:block text-slate-600">
                  <ArrowRight className="w-6 h-6" />
                </div>

                {/* Step 2 */}
                <div className="bg-[#020408] border border-white/10 p-6 rounded-xl w-full md:w-64 h-48 flex flex-col items-center justify-center text-center group hover:border-indigo-500/30 transition-all">
                  <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center mb-4 text-white font-bold group-hover:bg-indigo-600 transition-colors">
                    2
                  </div>
                  <h4 className="text-white font-medium mb-1">
                    Platform Scope
                  </h4>
                  <p className="text-xs text-slate-500">
                    Assets & Algorithm selection
                  </p>
                </div>

                {/* Arrow */}
                <div className="hidden md:block text-slate-600">
                  <ArrowRight className="w-6 h-6" />
                </div>

                {/* Step 3 */}
                <div className="bg-gradient-to-br from-blue-900/20 to-indigo-900/20 border border-blue-500/20 p-6 rounded-xl w-full md:w-64 h-48 flex flex-col items-center justify-center text-center shadow-lg shadow-blue-900/10">
                  <div className="w-10 h-10 rounded-full bg-white text-blue-900 flex items-center justify-center mb-4 font-bold shadow-lg">
                    <Check className="w-4 h-4" strokeWidth={3} />
                  </div>
                  <h4 className="text-white font-medium mb-1">
                    Your Custom Price
                  </h4>
                  <p className="text-xs text-blue-200/60">
                    Tailored to your needs
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Partnership Tiers */}
          <div className="mb-24">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-semibold text-white mb-4">
                Choose Your Partnership Level
              </h2>
              <p className="text-slate-400">
                All pricing is customized, but these tiers help structure your
                solution
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
              {/* Tier 1 - Starter */}
              <div className="bg-[#0B0E14] border border-white/10 rounded-2xl p-8 hover:border-white/20 transition-all">
                <h3 className="text-xl font-semibold text-white mb-2">
                  Starter
                </h3>
                <p className="text-sm text-slate-400 mb-6 min-h-[40px]">
                  Perfect for agencies testing algorithmic trading with a select
                  client group.
                </p>
                <div className="space-y-4 mb-8">
                  {[
                    "1-2 Markets",
                    "10 Core Strategies",
                    "Up to 50 Clients",
                    "Basic White-Label",
                  ].map((feature) => (
                    <div
                      key={feature}
                      className="flex items-center gap-3 text-sm text-slate-300"
                    >
                      <div className="w-5 h-5 rounded-full bg-white/10 flex items-center justify-center">
                        <Check className="w-3 h-3" />
                      </div>
                      {feature}
                    </div>
                  ))}
                </div>
                <button className="w-full py-3 bg-white text-black rounded-lg font-semibold hover:bg-slate-200 transition-colors">
                  Request Starter Quote
                </button>
              </div>

              {/* Tier 2 - Growth (Most Popular) */}
              <div className="bg-[#0B0E14] border border-blue-500/30 rounded-2xl p-8 shadow-2xl shadow-blue-900/20 relative transform md:-translate-y-4">
                <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider shadow-lg">
                  Most Popular
                </div>
                <h3 className="text-xl font-semibold text-white mb-2 flex items-center gap-2">
                  Growth <span className="text-blue-400">✦</span>
                </h3>
                <p className="text-sm text-slate-400 mb-6 min-h-[40px]">
                  For established agencies ready to scale operations and
                  revenue.
                </p>
                <div className="space-y-4 mb-8">
                  {[
                    "2-3 Markets",
                    "25 Premium Strategies",
                    "Up to 200 Clients",
                    "Advanced Integrations",
                    "Account Manager",
                  ].map((feature) => (
                    <div
                      key={feature}
                      className="flex items-center gap-3 text-sm text-white font-medium"
                    >
                      <div className="w-5 h-5 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center">
                        <Check className="w-3 h-3" />
                      </div>
                      {feature}
                    </div>
                  ))}
                </div>
                <button className="w-full py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-semibold transition-all shadow-lg shadow-blue-900/20">
                  Request Growth Quote
                </button>
              </div>

              {/* Tier 3 - Enterprise */}
              <div className="bg-[#0B0E14] border border-white/10 rounded-2xl p-8 hover:border-white/20 transition-all">
                <h3 className="text-xl font-semibold text-white mb-2">
                  Enterprise
                </h3>
                <p className="text-sm text-slate-400 mb-6 min-h-[40px]">
                  For large institutions requiring full customization and
                  unlimited scale.
                </p>
                <div className="space-y-4 mb-8">
                  {[
                    "All 4 Markets",
                    "Full 30+ Library",
                    "Unlimited Clients",
                    "Custom Development",
                  ].map((feature) => (
                    <div
                      key={feature}
                      className="flex items-center gap-3 text-sm text-slate-300"
                    >
                      <div className="w-5 h-5 rounded-full bg-white/10 flex items-center justify-center">
                        <Check className="w-3 h-3" />
                      </div>
                      {feature}
                    </div>
                  ))}
                </div>
                <button className="w-full py-3 bg-white/5 text-white border border-white/10 rounded-lg font-semibold hover:bg-white/10 transition-colors">
                  Request Enterprise Quote
                </button>
              </div>
            </div>
          </div>

          {/* ROI Calculator Preview */}
          <div className="mb-24">
            <div className="rounded-2xl border border-white/5 bg-[#0B0E14] overflow-hidden">
              <div className="p-8 md:p-12 text-center">
                <h2 className="text-3xl font-semibold text-white mb-2">
                  See Your Potential ROI
                </h2>
                <p className="text-slate-400 mb-10">
                  The platform is designed to pay for itself quickly through
                  client commissions
                </p>

                <div className="max-w-3xl mx-auto bg-[#020408] border border-white/10 rounded-xl p-6 md:p-8">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
                    <div className="text-left">
                      <label className="text-xs text-slate-500 uppercase font-semibold mb-2 block">
                        Number of Clients
                      </label>
                      <div className="h-2 bg-white/10 rounded-full mb-2">
                        <div className="w-1/4 h-full bg-blue-500 rounded-full" />
                      </div>
                      <div className="text-xl font-mono text-white">50</div>
                    </div>
                    <div className="text-left">
                      <label className="text-xs text-slate-500 uppercase font-semibold mb-2 block">
                        Avg Account Size
                      </label>
                      <div className="h-2 bg-white/10 rounded-full mb-2">
                        <div className="w-1/2 h-full bg-blue-500 rounded-full" />
                      </div>
                      <div className="text-xl font-mono text-white">
                        $50,000
                      </div>
                    </div>
                    <div className="text-left">
                      <label className="text-xs text-slate-500 uppercase font-semibold mb-2 block">
                        Avg Annual Return
                      </label>
                      <div className="h-2 bg-white/10 rounded-full mb-2">
                        <div className="w-1/3 h-full bg-blue-500 rounded-full" />
                      </div>
                      <div className="text-xl font-mono text-white">15%</div>
                    </div>
                  </div>

                  <div className="bg-gradient-to-r from-blue-900/20 to-indigo-900/20 border border-blue-500/20 rounded-lg p-6 flex flex-col md:flex-row items-center justify-between gap-4">
                    <div>
                      <p className="text-sm text-slate-400">
                        Your Potential Annual Commission
                      </p>
                      <p className="text-xs text-slate-500">
                        (Based on standard 20% performance fee)
                      </p>
                    </div>
                    <div className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-400">
                      $75,000
                      <span className="text-lg text-slate-500 font-medium">
                        /year
                      </span>
                    </div>
                  </div>
                </div>

                <button className="mt-8 text-sm text-slate-400 hover:text-white flex items-center justify-center gap-2 mx-auto transition-colors">
                  <Calculator className="w-4 h-4" />
                  Calculate your specific scenario
                </button>
              </div>
            </div>
          </div>

          {/* No Hidden Fees */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-24">
            <div className="bg-[#0B0E14] border border-white/5 rounded-2xl p-8">
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-emerald-500" />
                Included at No Extra Cost
              </h3>
              <ul className="space-y-4">
                {[
                  "Platform hosting & maintenance",
                  "Regular software updates",
                  "Security & compliance infrastructure",
                ].map((item) => (
                  <li
                    key={item}
                    className="flex items-center gap-3 text-slate-300"
                  >
                    <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-[#0B0E14] border border-white/5 rounded-2xl p-8">
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <PlusCircle className="w-5 h-5 text-blue-400" />
                Optional Add-ons
              </h3>
              <ul className="space-y-4">
                {[
                  "Custom algorithm development",
                  "Premium institutional data feeds",
                  "Dedicated server infrastructure",
                ].map((item) => (
                  <li
                    key={item}
                    className="flex items-center gap-3 text-slate-300"
                  >
                    <div className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* FAQ */}
          <div className="max-w-3xl mx-auto mb-24">
            <h3 className="text-2xl font-semibold text-white mb-8 text-center">
              Pricing Questions Answered
            </h3>
            <div className="space-y-4">
              {faqItems.map((faq, i) => (
                <div
                  key={i}
                  className="border border-white/5 rounded-lg bg-white/[0.02] overflow-hidden"
                >
                  <button
                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                    className="w-full p-4 flex items-center justify-between cursor-pointer hover:bg-white/5 transition-colors"
                  >
                    <span className="text-sm font-medium text-white text-left">
                      {faq.question}
                    </span>
                    <ChevronDown
                      className={`w-4 h-4 text-slate-500 transition-transform ${
                        openFaq === i ? "rotate-180" : ""
                      }`}
                    />
                  </button>
                  {openFaq === i && (
                    <div className="px-4 pb-4">
                      <p className="text-sm text-slate-400">{faq.answer}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Consultation Process */}
          <div className="mb-24">
            <div className="text-center mb-12">
              <h3 className="text-2xl font-semibold text-white mb-2">
                Your Path to Partnership Pricing
              </h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative">
              {/* Line */}
              <div className="hidden md:block absolute top-8 left-0 w-full h-px bg-white/10 -z-10" />

              {[
                {
                  icon: Calendar,
                  color: "text-blue-400",
                  title: "Book Consultation",
                  sub: "Choose a time",
                },
                {
                  icon: MessageSquare,
                  color: "text-indigo-400",
                  title: "Discovery",
                  sub: "We align on goals",
                },
                {
                  icon: FileText,
                  color: "text-purple-400",
                  title: "Custom Proposal",
                  sub: "Receive options",
                },
                {
                  icon: Rocket,
                  color: "text-emerald-400",
                  title: "Launch",
                  sub: "Start onboarding",
                },
              ].map((step, i) => {
                const Icon = step.icon;
                return (
                  <div key={i} className="text-center">
                    <div
                      className={`w-16 h-16 rounded-full bg-[#020408] border border-white/10 flex items-center justify-center mx-auto mb-4 ${step.color} z-10 relative`}
                    >
                      <Icon className="w-6 h-6" />
                    </div>
                    <h5 className="text-white font-medium mb-1">
                      {step.title}
                    </h5>
                    <p className="text-xs text-slate-500">{step.sub}</p>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Guarantees */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-24">
            {[
              {
                color: "bg-emerald-500",
                title: "30-Day Success Guarantee",
                desc: "Not satisfied? We'll make it right or refund your setup fee.",
              },
              {
                color: "bg-blue-500",
                title: "Pricing Lock",
                desc: "Your structure is locked in—no surprise increases.",
              },
              {
                color: "bg-purple-500",
                title: "Performance Model",
                desc: "We only profit when your clients profit.",
              },
            ].map((item, i) => (
              <div
                key={i}
                className="p-6 rounded-xl bg-white/[0.02] border border-white/5"
              >
                <div className="flex items-center gap-3 mb-3">
                  <div className={`w-2 h-2 rounded-full ${item.color}`} />
                  <h4 className="text-white font-semibold text-sm">
                    {item.title}
                  </h4>
                </div>
                <p className="text-xs text-slate-400">{item.desc}</p>
              </div>
            ))}
          </div>

          {/* Final CTA */}
          <div className="rounded-2xl bg-gradient-to-r from-blue-900/20 to-indigo-900/20 border border-blue-500/20 p-8 md:p-12">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
              <div>
                <h3 className="text-2xl font-semibold text-white mb-4">
                  Ready to Discuss Your Custom Pricing?
                </h3>
                <p className="text-slate-400 mb-6">
                  Schedule a 30-minute consultation with our partnership team. No
                  obligation, just clear answers.
                </p>
                <button className="w-full md:w-auto px-8 py-4 bg-white text-[#020408] rounded-full font-semibold hover:bg-slate-200 transition-all flex items-center justify-center gap-2">
                  Book Your Consultation
                  <Calendar className="w-4 h-4" />
                </button>
                <p className="text-xs text-slate-500 mt-4">
                  Typical response time: Under 2 hours during business days
                </p>
              </div>
              <div className="border-l border-white/10 md:pl-12">
                <h4 className="text-white font-medium mb-4">
                  Or Start by Learning More
                </h4>
                <ul className="space-y-3 mb-6">
                  {[
                    "Partnership Guide PDF",
                    "Feature Comparison Sheet",
                    "ROI Calculator Model",
                  ].map((item) => (
                    <li
                      key={item}
                      className="flex items-center gap-2 text-sm text-slate-400"
                    >
                      <div className="w-1.5 h-1.5 rounded-full bg-slate-600" />
                      {item}
                    </li>
                  ))}
                </ul>
                <button className="text-sm font-semibold text-white hover:text-blue-400 transition-colors flex items-center gap-2">
                  Download Partnership Kit
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
